# Automatically generated by Pynguin.
import pytest
import speedAtIntersection as module_0


def test_case_0():
    int_0 = 2
    float_0 = -870.20877
    float_1 = -3592.65
    var_0 = module_0.SpeedAtIntersection(int_0, float_1, float_0)
    assert var_0 == pytest.approx(-3309.561991167634, abs=0.01, rel=0.01)
    int_1 = 537
    var_1 = module_0.ReachIntersection(int_0, float_0, float_0, int_1)
    assert var_1 == pytest.approx(-796.104402432, abs=0.01, rel=0.01)
    int_2 = 4199
    var_2 = module_0.SetFinalSpeed(float_0, float_1, int_2, int_2)
    assert var_2 == pytest.approx(-483.87437540000025, abs=0.01, rel=0.01)
    int_3 = -2936
    float_2 = -1196.59
    int_4 = -1353
    int_5 = -576
    var_3 = module_0.SetFinalSpeed(float_2, float_0, int_4, int_5)
    assert var_3 == pytest.approx(-876.7363945999999, abs=0.01, rel=0.01)
    var_4 = module_0.ReachIntersection(int_0, float_0, float_0, int_3)
    assert var_4 == pytest.approx(-796.104402432, abs=0.01, rel=0.01)
    float_3 = 1248.5906
    var_5 = module_0.SpeedAtIntersection(int_0, float_3, float_3)
    assert var_5 == pytest.approx(1258.3906, abs=0.01, rel=0.01)


def test_case_1():
    int_0 = -204
    int_1 = 2
    float_0 = -3592.65
    float_1 = 617.47
    float_2 = 1091.977
    var_0 = module_0.SpeedAtIntersection(int_0, float_1, float_2)
    assert var_0 == pytest.approx(634.8010032876091, abs=0.01, rel=0.01)
    int_2 = 4199
    var_1 = module_0.SetFinalSpeed(float_1, float_0, int_0, int_2)
    assert var_1 == pytest.approx(-2180.0968000000003, abs=0.01, rel=0.01)
    int_3 = -2936
    int_4 = -564
    var_2 = module_0.SetFinalSpeed(float_2, float_1, int_0, int_4)
    assert var_2 == pytest.approx(163.8239, abs=0.01, rel=0.01)
    var_3 = module_0.ReachIntersection(int_1, float_2, float_2, int_3)
    assert var_3 == pytest.approx(1090.997, abs=0.01, rel=0.01)
    var_4 = module_0.SpeedAtIntersection(int_0, float_1, float_1)
    assert var_4 == pytest.approx(627.27, abs=0.01, rel=0.01)


def test_case_2():
    int_0 = 1
    float_0 = 617.47
    float_1 = 1091.3147485341747
    int_1 = -2955
    int_2 = -1394
    var_0 = module_0.SetFinalSpeed(float_0, float_0, int_2, int_1)
    assert var_0 == pytest.approx(-782.9382400000001, abs=0.01, rel=0.01)
    var_1 = module_0.ReachIntersection(int_0, float_1, float_1, int_1)
    assert var_1 == pytest.approx(1101.1147485341746, abs=0.01, rel=0.01)
